### ISSUE TITLE
npm中的版本号大于源码中的版本号，所以这里的源码并不是最新的吗？

### ISSUE THREAD

**Issue by cnryb** [openkraken/cli#8]
源代码中版本是0.7.3。在npm中的版本是 0.8.0 。
https://github.com/openkraken/cli/blob/5ed7b46e1da7b318d53efe4923459095e71a050d/package.json#L3

**Comment by andycall** [comment]
0.8.1 的 cli 之前还没有发布，现在发布了

https://github.com/openkraken/cli/pull/9

**Comment by cnryb** [comment]
没注意到正在release。  
我把代码拉下来之后发现编译不过，正准备上手改一改，就发现不一致了。
